name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build_on_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
      
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: m3u8-downloader-linux
        path: m3u8-downloader
        retention-days: 5
        
  build_on_windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
    
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: m3u8-downloader-win.exe
        path: m3u8-downloader.exe
        retention-days: 5
      
  build_on_macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: go build -v ./...
      
    - name: Test
      run: go test -v ./...
      
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: m3u8-downloader-mac
        path: m3u8-downloader
        retention-days: 5
